WIP
hellobloom/share-kit-flutter pull request #1
Opened 2019-04-30 14:07 UTC by touhonoob

- [x] port merkeltree
- [x] port ethereum utils
- [ ] port attestation-lib
- [ ] port share-kit

2019-05-14 01:19 UTC, JaceHensley requested changes
Pulled down the repo and the stories look great! Just a few things from looking at the code. Thanks again!

2019-05-14 01:19 UTC, JaceHensley commented on lib/src/elements/request_button.dart
> +        'https://bloom.co/download?request=${base64.encode(utf8.encode(jsonEncode(requestData.toJson())))}&callback_url=${Uri.encodeComponent(buttonCallbackUrl)}&share-kit-from=button';
The `share-kit-from=button` query param should be added to `requestData.url` not the url that is launched to open the Bloom app

2019-05-14 01:19 UTC, JaceHensley commented on lib/src/elements/request_button.dart
> +    urlLauncher.launchUrl(url);
I think this is missing an `await`

2019-05-14 01:19 UTC, JaceHensley commented on lib/src/elements/request_qr_code.dart
> +import 'dart:convert';
We actually don't need QR code related things in the flutter version. Since the QR code stuff is only needed for desktop platforms.

2019-05-14 01:19 UTC, JaceHensley commented on lib/src/types.dart
> +class QROptions {
Isn't needed

2019-05-14 01:19 UTC, JaceHensley commented on lib/src/types.dart
> +class ParsedResult {
The `bowser` types aren't needed or used in this lib

2019-05-14 01:19 UTC, JaceHensley commented on lib/src/types.dart
> +typedef bool ShouldRenderButton(ParsedResult parsedResult);
Not needed/used

2019-05-14 01:19 UTC, JaceHensley commented on lib/src/types.dart
> +class RequestElementResultUpdateConfig {
Not needed/used

2019-05-14 01:19 UTC, JaceHensley commented on lib/src/types.dart
> +typedef void RequestElementResultUpdateFunction(
Not needed/used

2019-05-14 01:19 UTC, JaceHensley commented on lib/src/types.dart
> +typedef void RequestElementResultRemoveFunction();
Not needed/used

2019-05-14 01:19 UTC, JaceHensley commented on lib/src/types.dart
> +class RequestElementResult {
Not needed/used

2019-05-14 01:19 UTC, JaceHensley commented on lib/src/types.dart
> +// Response Types
The response types also don't need to be included since that is for the server side of things

2019-05-14 01:21 UTC, JaceHensley commented
@touhonoob actually you can leave the QR stuff, thanks!

2019-05-14 02:02 UTC, touhonoob commented
@JaceHensley Thanks for the review. Updated accordingly in the latest commits.

2019-05-15 16:25 UTC, JaceHensley approved these changes
Looks great! I'll merge this now and get it published on pub

2019-05-15 16:27 UTC, merged